### ISSUE TITLE
Disambiguate grammar

### ISSUE THREAD

**Issue by SanderJSA** [jinko-core/jinko#269]
Currently it is impossible to write a parser that runs in O(n) because of ambiguity caused by type instantiation and blocks, for instance:
```
if thing { a = 1 } ...
```
A parser cannot know whether:
- this is 'if' followed by a type instantiation `thing` with the attribute `a` set to 1
- this is 'if' followed by a variable `thing` and a block that contains a variable assignment `a = 1`
The only way to know is by trying one option, parsing up until an error and if it fails try the other option.

This causes multiple issues:
- the parser cannot run in linear time, which causes performance issues in some cases.
- a backtracking free parser can tell exactly the location of the input that is a parsing error, once backtracking is introduced the parser cannot know which of the two paths was the one the user was trying to take, meaning location cannot be set further than the point at which the ambiguity starts.

The ambiguous rules I found so far were Type instantiation when used inside an If, While or a For expression.

For reference purposes here's a grammar of Jinko I'm currently working on implementing that is LL(1) except in these two cases
```
expr = term ( '+' term | '-' term )*

term = factor next ( '*' factor next | '/' factor next )*

factor = next unit factor_rest
factor_rest = '.' IDENTIFIER next method_or_field factor_rest
            | ε
method_or_field = '(' args
                | ε

unit = 'if' expr block next [ 'else' next block ]
     | 'while' expr block
     | 'loop' next block
     | 'for' next IDENTIFIER next 'in' expr block
     | 'type' next IDENTIFIER next '{' named_args
     | 'incl' next IDENTIFIER next [ 'as' next IDENTIFIER ]
     | 'mut' next IDENTIFIER next '=' expr (* mutable variable assigment *)
     | '@' next IDENTIFIER next '(' args
     | 'func' function_declaration block
     | 'test' function_declaration block
     | 'mock' function_declaration block
     | 'extern' 'func' function_declaration ';'
     | 'return' expr
     | '{' next inner_block
     | 'true'
     | 'false'
     | "'" CHAR "'"
     | '"' [^"] '"'
     | INT
     | DOUBLE
     | IDENTIFIER next func_type_or_var

method_or_field = '(' args                 (* method call *)
                | ε                        (* field access *)

func_type_or_var = '(' args                (* function_call *)
                 | '{' named_args          (* type instanciation *)
                 | '=' expr                (* variable assigment *)
                 | ε                       (* variable *)

block = '{' next inner_block
inner_block = expr ( ';' expr )* '}'
            | '}'

function_declaration = next IDENTIFIER next '(' typed_args next return_type
return_type = '->' next IDENTIFIER next
            | ε

typed_args = typed_arg ( ',' typed_arg )* ')'
           | ')'
typed_arg = next IDENTIFIER next ':' next IDENTIFIER next

named_args = named_arg ( ',' named_arg )* '}'
           | '}'
named_arg = next IDENTIFIER next '=' next expr next

args = expr ( ',' expr )* ')'
     | ')'

next = extra*

extra = WHITESPACE
      | '/*' [^'*/'] '*/'
      | '//' [^\n] '\n'
      | '#'  [^\n] '\n'
```

**Comment by CohenArthur** [comment]
I'd like for the parser and the rules of the language to keep simple. To me, it is important that any expression should be able to be parsed as a condition for an if-else block, and that the differenciation be done at typechecking. I'd like for all of these to be valid:
```rust
if true { ... }
if { true } { ... }
if {
    global_var = mutated_value;
    global_var = some_fn_call(global_var);
    global_var.is_valid()
 } { ... }
 if CustomType(field: value, field_other: value).is_valid() { ... }
 ```
And of course to not allow, but at typechecking, to not use something returning a boolean as a condition.

**Comment by SanderJSA** [comment]
Here's a new candidate for function_calls and type_instantiation:
```
function_call = IDENTIFIER '(' [ arg ( ',' arg)* ( ',' named_arg)* ] ')'
type_instantiation = IDENTIFIER '(' typed_arg+ ')'
```
What do you think ?
