### ISSUE TITLE
Typechecking is not correct on variable assignments

### ISSUE THREAD

**Issue by CohenArthur** [jinko-core/jinko#522]
```rust
a = b = 15;
b = { println("jinko"); };
```

Both of these should fail typechecking instead of failing interpretetation

**Comment by Skallwar** [comment]
Why the first one should fail ?

**Comment by CohenArthur** [comment]
Because `b = 15` is a statement (for now, at least) and thus produces no values. And you shouldn't be able to assign a statement to a variable, similarly to how you can't assign `void` in C
