### ISSUE TITLE
Missing check in pull-request step

### ISSUE THREAD

**Issue by CohenArthur** [jinko-core/jinko#549]
Currently, master is broken despite the CI passing on the pull-request. The failure occurs in the `docker build` part of the CI, which indicates that we should probably have one more check in the pull-request CI

**Comment by tanguysegarra** [comment]
The specific issue we are talking about has been fixed.
Still, I agree the behaviour was really weird with a green PR but a red master, but almost look like bad luck. Unfortunately it is impossible de retrieve the logs as they are too old.
Also, I checked and all workflows are triggered both for pull requests and master.
I don't really see what check we can add, do you have something in mind?

**Comment by CohenArthur** [comment]
Not really, seems fine to me now :) Thanks for working on it!
